### ISSUE TITLE
Support for taint mode?

### ISSUE THREAD

**Issue by xipmix** [plicease/Test-Script#13]
This may be just me not understanding what to do, but as far as I can see there is no support for running scripts with -T. Perhaps there is another way to invoke taint mode I am unaware of.

```
% cat scriptwith-T.pl
#!/usr/bin/env perl -T

print "Hi!\n";

% cat t/01.t 
#!/usr/bin/env perl

use strict;
use warnings;

use Test::Script;
use Test::More tests => 2;


my $s = 'scriptwith-T.pl';
script_compiles($s);
script_runs($s);


% prove t/01.t 
t/01.t .. 1/2 
#   Failed test 'Script scriptwith-T.pl compiles'
#   at t/01.t line 11.
# 255 - "-T" is on the #! line, it must also be used on the command line at ./scriptwith-T.pl line 1.

#   Failed test 'Script scriptwith-T.pl runs'
#   at t/01.t line 12.
# 255 - "-T" is on the #! line, it must also be used on the command line at ./scriptwith-T.pl line 1.
# Looks like you failed 2 tests of 2.
t/01.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 

Test Summary Report
-------------------
t/01.t (Wstat: 512 Tests: 2 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
Files=1, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.02 cusr  0.00 csys =  0.05 CPU)
Result: FAIL
```
I get the same result if I add -T to the hashbang line of t/01.t.

**Comment by plicease** [comment]
Please try 0.17_01, I believe it should address this.

https://metacpan.org/pod/release/PLICEASE/Test-Script-1.17_01/lib/Test/Script.pm

I should be able to do a prod release later in the week.

**Comment by xipmix** [comment]
It seems to be working, thank you very much!
Tested on Debian Jessie
  perl                5.20.2
  IPC::Run3           0.048
  Test::Builder       1.001008

**Comment by plicease** [comment]
Sending to CPAN as 0.18. Thank you for reporting this!
