### ISSUE TITLE
stdin on scalar reference doesn't work on 1.19_2

### ISSUE THREAD

**Issue by nigelhorne** [plicease/Test-Script#23]
It worked fine on 1.18, however the new version doesn't seem to use the input.  See https://github.com/nigelhorne/CGI-Info/blob/master/t/bin.t which tests fine on 1.18 but hangs waiting to read from STDIN with 1.19_2.

**Comment by plicease** [comment]
Thank you for reporting this.  This will block any production release.

**Comment by plicease** [comment]
Can you please try this with 1.19_04?  It should be fixed in that version on its way to CPAN.

**Comment by nigelhorne** [comment]
Yes, thanks. Looks much better.

**Comment by plicease** [comment]
closing then.  Gonna wait for some cpantsters feedback before doing a production release.
