### ISSUE TITLE
Options to the perl interpreter to be set from Test::Script

### ISSUE THREAD

**Issue by marekro** [plicease/Test-Script#24]
What is the way to pass through command line options to the underlying Perl interpreter from within Test::Script? The particular issue I am having is that we need "perl -x" to skip a special header - and I didn't find a way to specify the "-x".
Would you consider this an enhancement request? Other possible applications could be adding profiling or code coverage options.
Thank you!

**Comment by plicease** [comment]
Normally I would recommend the `PERL5OPT` environment variable, something like

```perl
  {
    local $ENV{PERL5OPT} = '-I/foo';
    script_runs( ... );
  }
```

but checking the `perlrun` man page it says that only `−[CDIMUdmtwW]` switches are allowed.  I think we could probably add a command line switches option to the optional `\%options` hash that would be passed into the Perl executable.  Do you need this for `script_compiles`?  That doesn't currently have an `\%options` hash ref, but I think we could add it.

**Comment by marekro** [comment]
Exactly - we'd need it for script_compile, but also for script_runs (and additional checks on exit status, and stodout/stderr output). Yes, an option (array ref) with additional command line arguments/options to be set on the "perl ..." command line would be precisely what we need. I saw that script_compiles() already has an option hash ref, so here an additional key could be added (btw: the option keys do not seem to be documented in POD?). For script_compiles(), an optional hashref could be added to the sub arguments. Ok?

**Comment by plicease** [comment]
The `\%options` hash ref keys are documented here: 
https://metacpan.org/pod/Test::Script#exit

**Comment by plicease** [comment]
`0.24_01` adds interpreter_options option to the `script_runs`. I decided not to add `\%options` to `script_compiles` (at lest for now) as I think it complicates the interfaces and you can do the equivalent by:

```perl
use Test::Script qw( script_runs );
script_runs $script, { interpreter_options => [ '-c', ... ], ... };
```

I think this should do what you need.  I can make a production release in a few days if it looks good in testing.

**Comment by plicease** [comment]
This is in 0.25, the latest production release.
