### ISSUE TITLE
Request: ability to test non-Perl programs

### ISSUE THREAD

**Issue by cxw42** [plicease/Test-Script#26]
I would like to do just what Test::Script does, but against arbitrary executables (i.e., don't start the `system()` arg list with `perl()`).  Is that something you would be willing to add or accept a PR for?  The use case is replacing the basic functionality of ctest with something that has sane escaping and cross-platform support (e.g., perhaps with Win/Unix shell quoting a la Argv, ShellQuote::Any, &c.).

Thanks for considering this request!

Chris (CXW)

**Edit** Thanks for the quick response!

**Comment by plicease** [comment]
Yes.  I've wished that `Test::Script` had this capability, but lacking tuits has never happened.

**Comment by plicease** [comment]
Just to be explicit, yes to a PR.  I still lack the tuits to implement this myself atm, but I will have time to review a PR, and hopefully merge and release if all goes well.

**Comment by cxw42** [comment]
From a quick look, 95% of the PR will be the new test files!  Actually adding the new functions should just be a small refactor.

**Comment by cxw42** [comment]
TUITS! :D :D  Anyway, I look forward to your comments on #27 whenever you have a chance :) .  Thanks!
