### ISSUE TITLE
Documentation should display which versions have which features

### ISSUE THREAD

**Issue by robrwo** [plicease/Test-Script#30]
If it explicitly requires Test2::V0 instead of (older versions of) Test::More, then the SYNOPSIS should be updated:
```perl
use Test2::V0;
use Test::Script 1.23;
 
script_compiles('script/myscript.pl');
script_runs(['script/myscript.pl', '--my-argument']);
 
done_testing;
```

**Comment by plicease** [comment]
All versions of `Test::Script` should work with either `Test2::V0` (or `Test::More` for that matter) via the appropriate version of `Test::Builder` or `Test2::API`, so explicitly requiring a specific version of `Test::Script` should not be necessary.

**Comment by robrwo** [comment]
I've had test failures on one of my modules, http://www.cpantesters.org/cpan/report/73f6b917-6c00-1014-9bfe-096dbf37bdb4

This seems to have been fixed by adding the minimum version.

**Comment by plicease** [comment]
That test is relying on a feature introduced in 1.09, I don't believe it has anything to do with Test2.

https://metacpan.org/changes/distribution/Test-Script#L110

**Comment by robrwo** [comment]
In that case, it's probably worth identifying which version uses what features in the POD.

**Comment by plicease** [comment]
Happy to review PRs that will add this information to the main documentation.  Everything should be covered in the Changes file, but to have it in the POD would be helpful.  My preferred  way of indicating version information can be seen in the `FFI::Platypus` documentation:

https://metacpan.org/pod/FFI::Platypus#ignore_not_found
