### ISSUE TITLE
Warning: Use of "quotemeta" without parentheses is ambiguous

### ISSUE THREAD

**Issue by SineSwiper** [plicease/Test-Script#7]
Apparently, older Perls don't like this.  Easy fix, though:

    --- lib/Test/Script.pm
    +++ lib/Test/Script.pm
    @@ -131,7 +131,7 @@ sub _preload_module
         join ',', 
         # quotemeta is overkill, but it will make sure that characters
         # like " are quoted
    -    map { '"' . quotemeta . '"' }
    +    map { '"' . quotemeta() . '"' }
         grep { ! ref } @INC)
           || die "unable to write $filename: $!";
       close($fh) || die "unable to close $filename: $!";;

**Comment by plicease** [comment]
I see a warning on Perl 5.8.1.  Out of curiosity, which version of Perl were you using where you saw this?

Thanks for reporting this!
